version: '3'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/stats
      - $PWD:/solrconfig
    entrypoint:
      - solr-precreate
      - stats
      - /solrconfig
volumes:
  data:
