version: "2"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.124.124.0/16

services:
  app:
    build: .
    environment:
       - SOLR_ADDRESS=http://solr:8983
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/bower_components

  solr:
    build:
      context: ./solrconfig
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - stats
      - /tmp/stats
