version: "2"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.124.124.0/16

services:
  app:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/bower_components

  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/stats
      - $PWD/solr_docker/solrconfig:/solrconfig
    entrypoint:
      - solr-precreate
      - stats
      - /solrconfig
  volumes:
    data:
